<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />

    <ProjectReference Include="..\..\EntityFramework\src\IdentityServer4.EntityFramework.csproj" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="$(DotNetLibrary10xx)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(DotNetLibrary10xx)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(DotNetLibrary10xx)" PrivateAssets="All" />
    
    <ProjectReference Include="..\src\IdentityServer4.csproj" />
  </ItemGroup>
</Project>