<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="$(DotNetLibrary10xx)" />
    
    <ProjectReference Include="..\src\IdentityServer4.Local.csproj" />
  </ItemGroup>
</Project>