<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonJson)" />

    <PackageReference Include="IdentityServer4.EntityFramework" Version="$(IdentityServer4)" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="$(DotNetLibrary3xx)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(DotNetLibrary3xx)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.12" PrivateAssets="All" />
    <PackageReference Include="System.Security.Principal.Windows" Version="4.7.0" />
    
    <ProjectReference Include="..\src\IdentityServer4.csproj" />
  </ItemGroup>
</Project>