<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <DotNetLibrary6xx>6.0.*</DotNetLibrary6xx>
    <DotNetLibrary8xx>8.0.*</DotNetLibrary8xx>
    <DotNetLibrary10xx>10.0.*</DotNetLibrary10xx>
    <OpenIdConnect>8.0.1</OpenIdConnect>
    <JsonLib>6.0.0</JsonLib>
    <IdentityModel>5.2.0</IdentityModel>
    <NewtonJson>13.0.1</NewtonJson>
    <AutoMapper>10.1.1</AutoMapper>
    <TestSdk>16.11.0</TestSdk>
  </PropertyGroup>

</Project>
