<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <DotNetLibrary6xx>6.0.*</DotNetLibrary6xx>
    <DotNetLibrary8xx>8.0.*</DotNetLibrary8xx>
    <DotNetLibrary10xx>10.0.*</DotNetLibrary10xx>
    <OpenIdConnect>8.1.*</OpenIdConnect>
    <IdentityModel>5.2.0</IdentityModel>
    <NewtonJson>13.0.*</NewtonJson>
    <AutoMapper>16.0.*</AutoMapper>
    <TestSdk>16.11.0</TestSdk>
  </PropertyGroup>

</Project>
