<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <AssemblyOriginatorKeyFile>../../../../key.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\IdentityServer4.EntityFramework.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.10.3" />

    <PackageReference Include="IdentityServer4" Version="$(IdentityServer4)" />
    <PackageReference Include="IdentityServer4.Storage" Version="$(IdentityServer4)" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(DotNetLibrary5xx)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(DotNetLibrary5xx)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(DotNetLibrary5xx)" />

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>  
  </ItemGroup>
</Project>