<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <PackageId>OidcForge</PackageId>
    <TargetFramework>net10.0</TargetFramework>
    <Description>OpenID Connect and OAuth 2.0 Framework for ASP.NET Core (maintained fork of IdentityServer4)</Description>
    <Authors>Brock Allen;Dominick Baier;Yaroslav Tatarenko</Authors>
    <AssemblyName>IdentityServer4</AssemblyName>
    <PackageTags>OAuth2;OAuth 2.0;OpenID Connect;Security;Identity;IdentityServer</PackageTags>
    <PackageIcon>icon.jpg</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/yartat/IdentityServer4</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReleaseNotes>https://github.com/yartat/IdentityServer4/blob/master/RELEASE_NOTES.md</PackageReleaseNotes>

    <!-- Declare that the Repository URL can be published to NuSpec -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Embed source files that are not tracked by the source control manager to the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Include PDB in the built .nupkg -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>

    <!-- strong naming fml -->
    <AssemblyOriginatorKeyFile>../../../key.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="../../../icon.jpg" Pack="true" Visible="false" PackagePath="" />
    <None Include="../README.md" Pack="true" Visible="false" PackagePath="" />
    <None Include="../../.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="Duende.IdentityModel" Version="$(DuendeIdentityModel)" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="$(OpenIdConnect)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="$(DotNetLibrary10xx)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Storage\src\IdentityServer4.Storage.csproj" />
  </ItemGroup>

</Project>