// Copyright (c) Yaroslav Tatarenko. All rights reserved.
// Part of a fork of IdentityServer4 (Copyright (c) Brock Allen & Dominick Baier).
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

namespace IdentityServer4.EntityFramework.Mappers
{
    /// <summary>
    /// Instances of the mappers generated by Mapster.Tool.
    /// </summary>
    /// <remarks>
    /// The GenerateMappers target builds this assembly with MAPSTER_CODEGEN defined and without Generated/*.g.cs,
    /// so the tool can run even when the generated code is missing or out of date.
    /// </remarks>
    internal static class GeneratedMappers
    {
#if MAPSTER_CODEGEN
        public static readonly IClientMapper Client = null;
        public static readonly IApiResourceMapper ApiResource = null;
        public static readonly IScopeMapper Scope = null;
        public static readonly IIdentityResourceMapper IdentityResource = null;
        public static readonly IPersistedGrantMapper PersistedGrant = null;
#else
        public static readonly IClientMapper Client = new ClientMapper();
        public static readonly IApiResourceMapper ApiResource = new ApiResourceMapper();
        public static readonly IScopeMapper Scope = new ScopeMapper();
        public static readonly IIdentityResourceMapper IdentityResource = new IdentityResourceMapper();
        public static readonly IPersistedGrantMapper PersistedGrant = new PersistedGrantMapper();
#endif
    }
}
