// Copyright (c) Yaroslav Tatarenko. All rights reserved.
// Part of a fork of IdentityServer4 (Copyright (c) Brock Allen & Dominick Baier).
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using Mapster;

namespace IdentityServer4.EntityFramework.Mappers
{
    /// <summary>
    /// Entity/model mapping for persisted grants. The implementation (<c>PersistedGrantMapper</c>) is generated by Mapster.Tool
    /// into Generated/PersistedGrantMapper.g.cs; run <c>dotnet build -t:GenerateMappers</c> after changing the mapping.
    /// </summary>
    [Mapper]
    internal interface IPersistedGrantMapper
    {
        Models.PersistedGrant ToModel(Entities.PersistedGrant entity);
        Entities.PersistedGrant ToEntity(Models.PersistedGrant model);
        Entities.PersistedGrant UpdateEntity(Models.PersistedGrant model, Entities.PersistedGrant entity);
    }
}
