// Copyright (c) Yaroslav Tatarenko. All rights reserved.
// Part of a fork of IdentityServer4 (Copyright (c) Brock Allen & Dominick Baier).
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using Mapster;

namespace IdentityServer4.EntityFramework.Mappers
{
    /// <summary>
    /// Entity/model mapping for API scopes. The implementation (<c>ScopeMapper</c>) is generated by Mapster.Tool
    /// into Generated/ScopeMapper.g.cs; run <c>dotnet build -t:GenerateMappers</c> after changing the mapping.
    /// </summary>
    [Mapper]
    internal interface IScopeMapper
    {
        Models.ApiScope ToModel(Entities.ApiScope entity);
        Entities.ApiScope ToEntity(Models.ApiScope model);
    }
}
